# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\DrumBurp\src\GUI\drumburp.ui'
#
# Created: Sun Sep 18 00:16:30 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DrumBurpWindow(object):
    def setupUi(self, DrumBurpWindow):
        DrumBurpWindow.setObjectName(_fromUtf8("DrumBurpWindow"))
        DrumBurpWindow.resize(965, 769)
        DrumBurpWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/drumburp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DrumBurpWindow.setWindowIcon(icon)
        DrumBurpWindow.setAnimated(True)
        DrumBurpWindow.setDockNestingEnabled(True)
        DrumBurpWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(DrumBurpWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setContentsMargins(5, 0, 1, 3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.frame_2 = QtGui.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.paperBox = QtGui.QComboBox(self.frame_2)
        self.paperBox.setObjectName(_fromUtf8("paperBox"))
        self.paperBox.addItem(_fromUtf8(""))
        self.paperBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.paperBox)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.VLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_8.addWidget(self.frame)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.widthSpinBox = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimum(10)
        self.widthSpinBox.setMaximum(1000)
        self.widthSpinBox.setProperty(_fromUtf8("value"), 80)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.horizontalLayout.addWidget(self.widthSpinBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.frame_5 = QtGui.QFrame(self.groupBox)
        self.frame_5.setFrameShape(QtGui.QFrame.VLine)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.frame_3 = QtGui.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineSpaceSlider = QtGui.QSlider(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSpaceSlider.sizePolicy().hasHeightForWidth())
        self.lineSpaceSlider.setSizePolicy(sizePolicy)
        self.lineSpaceSlider.setMaximum(100)
        self.lineSpaceSlider.setTracking(False)
        self.lineSpaceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lineSpaceSlider.setInvertedAppearance(False)
        self.lineSpaceSlider.setInvertedControls(False)
        self.lineSpaceSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.lineSpaceSlider.setObjectName(_fromUtf8("lineSpaceSlider"))
        self.horizontalLayout_9.addWidget(self.lineSpaceSlider)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.frame_6 = QtGui.QFrame(self.groupBox)
        self.frame_6.setFrameShape(QtGui.QFrame.VLine)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.groupBox)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.frame_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.defaultMeasureButton = QtGui.QPushButton(self.frame_7)
        self.defaultMeasureButton.setObjectName(_fromUtf8("defaultMeasureButton"))
        self.horizontalLayout_10.addWidget(self.defaultMeasureButton)
        self.horizontalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.groupBox)
        self.frame_8.setFrameShape(QtGui.QFrame.VLine)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.fontsButton = QtGui.QPushButton(self.groupBox)
        self.fontsButton.setObjectName(_fromUtf8("fontsButton"))
        self.horizontalLayout_8.addWidget(self.fontsButton)
        self.frame_9 = QtGui.QFrame(self.groupBox)
        self.frame_9.setFrameShape(QtGui.QFrame.VLine)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.sectionNavigator = QtGui.QComboBox(self.groupBox)
        self.sectionNavigator.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.sectionNavigator.setMinimumContentsLength(6)
        self.sectionNavigator.setDuplicatesEnabled(True)
        self.sectionNavigator.setObjectName(_fromUtf8("sectionNavigator"))
        self.horizontalLayout_8.addWidget(self.sectionNavigator)
        self.frame_10 = QtGui.QFrame(self.groupBox)
        self.frame_10.setFrameShape(QtGui.QFrame.VLine)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_8.addWidget(self.frame_10)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.scoreView = ScoreView(self.centralwidget)
        self.scoreView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.scoreView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scoreView.setAcceptDrops(False)
        self.scoreView.setLineWidth(1)
        self.scoreView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.scoreView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.scoreView.setObjectName(_fromUtf8("scoreView"))
        self.verticalLayout.addWidget(self.scoreView)
        DrumBurpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DrumBurpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecentScores = QtGui.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRecentScores.setIcon(icon1)
        self.menuRecentScores.setObjectName(_fromUtf8("menuRecentScores"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShowToolBars = QtGui.QMenu(self.menuView)
        self.menuShowToolBars.setObjectName(_fromUtf8("menuShowToolBars"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        DrumBurpWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DrumBurpWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DrumBurpWindow.setStatusBar(self.statusbar)
        self.fileToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.fileToolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fileToolBar.setMovable(True)
        self.fileToolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.fileToolBar.setIconSize(QtCore.QSize(32, 32))
        self.fileToolBar.setObjectName(_fromUtf8("fileToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolBar)
        self.displayToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.displayToolBar.setMovable(True)
        self.displayToolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.displayToolBar.setIconSize(QtCore.QSize(32, 32))
        self.displayToolBar.setObjectName(_fromUtf8("displayToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.displayToolBar)
        self.exportToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.exportToolBar.setIconSize(QtCore.QSize(32, 32))
        self.exportToolBar.setObjectName(_fromUtf8("exportToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.exportToolBar)
        self.helpToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.helpToolBar.setIconSize(QtCore.QSize(32, 32))
        self.helpToolBar.setObjectName(_fromUtf8("helpToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.helpToolBar)
        self.fontDock = QtGui.QDockWidget(DrumBurpWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontDock.sizePolicy().hasHeightForWidth())
        self.fontDock.setSizePolicy(sizePolicy)
        self.fontDock.setFloating(True)
        self.fontDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.fontDock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.fontDock.setObjectName(_fromUtf8("fontDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.fontComboBox = QtGui.QFontComboBox(self.groupBox_4)
        self.fontComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMinimumSize(QtCore.QSize(60, 20))
        self.fontComboBox.setMaximumSize(QtCore.QSize(187, 20))
        self.fontComboBox.setBaseSize(QtCore.QSize(100, 0))
        self.fontComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fontComboBox.setEditable(False)
        self.fontComboBox.setMaxVisibleItems(20)
        self.fontComboBox.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("BatangChe"))
        font.setPointSize(10)
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.horizontalLayout_3.addWidget(self.fontComboBox)
        self.noteSizeSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.noteSizeSpinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.noteSizeSpinBox.setMinimum(6)
        self.noteSizeSpinBox.setMaximum(30)
        self.noteSizeSpinBox.setProperty(_fromUtf8("value"), 10)
        self.noteSizeSpinBox.setObjectName(_fromUtf8("noteSizeSpinBox"))
        self.horizontalLayout_3.addWidget(self.noteSizeSpinBox)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sectionFontCombo = QtGui.QFontComboBox(self.groupBox_5)
        self.sectionFontCombo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionFontCombo.sizePolicy().hasHeightForWidth())
        self.sectionFontCombo.setSizePolicy(sizePolicy)
        self.sectionFontCombo.setMinimumSize(QtCore.QSize(60, 20))
        self.sectionFontCombo.setMaximumSize(QtCore.QSize(187, 20))
        self.sectionFontCombo.setBaseSize(QtCore.QSize(100, 0))
        self.sectionFontCombo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sectionFontCombo.setEditable(False)
        self.sectionFontCombo.setMaxVisibleItems(20)
        self.sectionFontCombo.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("BatangChe"))
        font.setPointSize(10)
        self.sectionFontCombo.setCurrentFont(font)
        self.sectionFontCombo.setObjectName(_fromUtf8("sectionFontCombo"))
        self.horizontalLayout_5.addWidget(self.sectionFontCombo)
        self.sectionFontSizeSpinbox = QtGui.QSpinBox(self.groupBox_5)
        self.sectionFontSizeSpinbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sectionFontSizeSpinbox.setMinimum(8)
        self.sectionFontSizeSpinbox.setMaximum(48)
        self.sectionFontSizeSpinbox.setProperty(_fromUtf8("value"), 20)
        self.sectionFontSizeSpinbox.setObjectName(_fromUtf8("sectionFontSizeSpinbox"))
        self.horizontalLayout_5.addWidget(self.sectionFontSizeSpinbox)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.metadataFontCombo = QtGui.QFontComboBox(self.groupBox_6)
        self.metadataFontCombo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataFontCombo.sizePolicy().hasHeightForWidth())
        self.metadataFontCombo.setSizePolicy(sizePolicy)
        self.metadataFontCombo.setMinimumSize(QtCore.QSize(60, 20))
        self.metadataFontCombo.setMaximumSize(QtCore.QSize(187, 20))
        self.metadataFontCombo.setBaseSize(QtCore.QSize(100, 0))
        self.metadataFontCombo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.metadataFontCombo.setEditable(False)
        self.metadataFontCombo.setMaxVisibleItems(20)
        self.metadataFontCombo.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("BatangChe"))
        font.setPointSize(10)
        self.metadataFontCombo.setCurrentFont(font)
        self.metadataFontCombo.setObjectName(_fromUtf8("metadataFontCombo"))
        self.horizontalLayout_4.addWidget(self.metadataFontCombo)
        self.metadataFontSizeSpinbox = QtGui.QSpinBox(self.groupBox_6)
        self.metadataFontSizeSpinbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.metadataFontSizeSpinbox.setMinimum(8)
        self.metadataFontSizeSpinbox.setMaximum(48)
        self.metadataFontSizeSpinbox.setProperty(_fromUtf8("value"), 20)
        self.metadataFontSizeSpinbox.setObjectName(_fromUtf8("metadataFontSizeSpinbox"))
        self.horizontalLayout_4.addWidget(self.metadataFontSizeSpinbox)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.fontDock.setWidget(self.dockWidgetContents_2)
        DrumBurpWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fontDock)
        self.MIDIToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.MIDIToolBar.setObjectName(_fromUtf8("MIDIToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.MIDIToolBar)
        self.actionQuit = QtGui.QAction(DrumBurpWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/system-log-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew = QtGui.QAction(DrumBurpWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionLoad = QtGui.QAction(DrumBurpWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon4)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(DrumBurpWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(DrumBurpWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon6)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionExportASCII = QtGui.QAction(DrumBurpWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/format-text-bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportASCII.setIcon(icon7)
        self.actionExportASCII.setObjectName(_fromUtf8("actionExportASCII"))
        self.actionDisplayOptionsIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionDisplayOptionsIsVisible.setCheckable(True)
        self.actionDisplayOptionsIsVisible.setObjectName(_fromUtf8("actionDisplayOptionsIsVisible"))
        self.actionFileToolbarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionFileToolbarIsVisible.setCheckable(True)
        self.actionFileToolbarIsVisible.setObjectName(_fromUtf8("actionFileToolbarIsVisible"))
        self.actionFitInWindow = QtGui.QAction(DrumBurpWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/video-display.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFitInWindow.setIcon(icon8)
        self.actionFitInWindow.setObjectName(_fromUtf8("actionFitInWindow"))
        self.actionToolbars = QtGui.QAction(DrumBurpWindow)
        self.actionToolbars.setObjectName(_fromUtf8("actionToolbars"))
        self.actionDisplayToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionDisplayToolBarIsVisible.setCheckable(True)
        self.actionDisplayToolBarIsVisible.setObjectName(_fromUtf8("actionDisplayToolBarIsVisible"))
        self.actionPrint = QtGui.QAction(DrumBurpWindow)
        self.actionPrint.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon9)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionWhatsThis = QtGui.QAction(DrumBurpWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/help-browser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWhatsThis.setIcon(icon10)
        self.actionWhatsThis.setObjectName(_fromUtf8("actionWhatsThis"))
        self.actionUndo = QtGui.QAction(DrumBurpWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon11)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(DrumBurpWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/edit-redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon12)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionExportPDF = QtGui.QAction(DrumBurpWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportPDF.setIcon(icon13)
        self.actionExportPDF.setObjectName(_fromUtf8("actionExportPDF"))
        self.actionAboutDrumBurp = QtGui.QAction(DrumBurpWindow)
        self.actionAboutDrumBurp.setIcon(icon)
        self.actionAboutDrumBurp.setObjectName(_fromUtf8("actionAboutDrumBurp"))
        self.actionExportToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionExportToolBarIsVisible.setCheckable(True)
        self.actionExportToolBarIsVisible.setObjectName(_fromUtf8("actionExportToolBarIsVisible"))
        self.actionHelpToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionHelpToolBarIsVisible.setCheckable(True)
        self.actionHelpToolBarIsVisible.setObjectName(_fromUtf8("actionHelpToolBarIsVisible"))
        self.actionShowEmptyLines = QtGui.QAction(DrumBurpWindow)
        self.actionShowEmptyLines.setCheckable(True)
        self.actionShowEmptyLines.setChecked(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/format-justify-fill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowEmptyLines.setIcon(icon14)
        self.actionShowEmptyLines.setObjectName(_fromUtf8("actionShowEmptyLines"))
        self.actionShowDrumKey = QtGui.QAction(DrumBurpWindow)
        self.actionShowDrumKey.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/1299815323_HAL-9000 Brain Room Key.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowDrumKey.setIcon(icon15)
        self.actionShowDrumKey.setObjectName(_fromUtf8("actionShowDrumKey"))
        self.actionShowScoreInfo = QtGui.QAction(DrumBurpWindow)
        self.actionShowScoreInfo.setCheckable(True)
        self.actionShowScoreInfo.setChecked(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/applications-multimedia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowScoreInfo.setIcon(icon16)
        self.actionShowScoreInfo.setObjectName(_fromUtf8("actionShowScoreInfo"))
        self.actionShowBeatCount = QtGui.QAction(DrumBurpWindow)
        self.actionShowBeatCount.setCheckable(True)
        self.actionShowBeatCount.setChecked(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/1299814882_Black_Numbered-List.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowBeatCount.setIcon(icon17)
        self.actionShowBeatCount.setObjectName(_fromUtf8("actionShowBeatCount"))
        self.actionFitPage = QtGui.QAction(DrumBurpWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/fit-page")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFitPage.setIcon(icon18)
        self.actionFitPage.setObjectName(_fromUtf8("actionFitPage"))
        self.actionPlayScore = QtGui.QAction(DrumBurpWindow)
        self.actionPlayScore.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/media-playback-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPlayScore.setIcon(icon19)
        self.actionPlayScore.setObjectName(_fromUtf8("actionPlayScore"))
        self.actionMuteNotes = QtGui.QAction(DrumBurpWindow)
        self.actionMuteNotes.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/audio-volume-medium.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/audio-volume-muted.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMuteNotes.setIcon(icon20)
        self.actionMuteNotes.setObjectName(_fromUtf8("actionMuteNotes"))
        self.actionExportMIDI = QtGui.QAction(DrumBurpWindow)
        self.actionExportMIDI.setObjectName(_fromUtf8("actionExportMIDI"))
        self.actionMIDIToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionMIDIToolBarIsVisible.setCheckable(True)
        self.actionMIDIToolBarIsVisible.setObjectName(_fromUtf8("actionMIDIToolBarIsVisible"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.menuRecentScores.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExportASCII)
        self.menuFile.addAction(self.actionExportPDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuShowToolBars.addAction(self.actionFileToolbarIsVisible)
        self.menuShowToolBars.addAction(self.actionDisplayToolBarIsVisible)
        self.menuShowToolBars.addAction(self.actionExportToolBarIsVisible)
        self.menuShowToolBars.addAction(self.actionMIDIToolBarIsVisible)
        self.menuShowToolBars.addAction(self.actionHelpToolBarIsVisible)
        self.menuView.addAction(self.actionFitInWindow)
        self.menuView.addAction(self.actionFitPage)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShowScoreInfo)
        self.menuView.addAction(self.actionShowDrumKey)
        self.menuView.addAction(self.actionShowEmptyLines)
        self.menuView.addAction(self.actionShowBeatCount)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDisplayOptionsIsVisible)
        self.menuView.addAction(self.menuShowToolBars.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionWhatsThis)
        self.menuHelp.addAction(self.actionAboutDrumBurp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.fileToolBar.addAction(self.actionNew)
        self.fileToolBar.addAction(self.actionLoad)
        self.fileToolBar.addAction(self.actionSave)
        self.fileToolBar.addAction(self.actionSaveAs)
        self.displayToolBar.addAction(self.actionFitInWindow)
        self.displayToolBar.addAction(self.actionFitPage)
        self.displayToolBar.addSeparator()
        self.displayToolBar.addAction(self.actionShowScoreInfo)
        self.displayToolBar.addAction(self.actionShowDrumKey)
        self.displayToolBar.addAction(self.actionShowEmptyLines)
        self.displayToolBar.addAction(self.actionShowBeatCount)
        self.exportToolBar.addAction(self.actionPrint)
        self.exportToolBar.addAction(self.actionExportASCII)
        self.exportToolBar.addAction(self.actionExportPDF)
        self.helpToolBar.addAction(self.actionWhatsThis)
        self.helpToolBar.addAction(self.actionAboutDrumBurp)
        self.MIDIToolBar.addAction(self.actionPlayScore)
        self.MIDIToolBar.addAction(self.actionMuteNotes)
        self.MIDIToolBar.addAction(self.actionExportMIDI)
        self.label_2.setBuddy(self.paperBox)
        self.label_3.setBuddy(self.widthSpinBox)
        self.label_4.setBuddy(self.lineSpaceSlider)
        self.label_5.setBuddy(self.defaultMeasureButton)

        self.retranslateUi(DrumBurpWindow)
        QtCore.QObject.connect(self.actionFileToolbarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fileToolBar.setVisible)
        QtCore.QObject.connect(self.fileToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionFileToolbarIsVisible.setChecked)
        QtCore.QObject.connect(self.displayToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDisplayToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.actionDisplayToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.displayToolBar.setVisible)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), DrumBurpWindow.close)
        QtCore.QObject.connect(self.actionExportToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.exportToolBar.setVisible)
        QtCore.QObject.connect(self.exportToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionExportToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.actionHelpToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.helpToolBar.setVisible)
        QtCore.QObject.connect(self.helpToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionHelpToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.fontDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDisplayOptionsIsVisible.setChecked)
        QtCore.QObject.connect(self.actionDisplayOptionsIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fontDock.setVisible)
        QtCore.QObject.connect(self.fontComboBox, QtCore.SIGNAL(_fromUtf8("currentFontChanged(QFont)")), self.scoreView.setFont)
        QtCore.QObject.connect(self.noteSizeSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setNoteFontSize)
        QtCore.QObject.connect(self.sectionFontSizeSpinbox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setSectionFontSize)
        QtCore.QObject.connect(self.sectionFontCombo, QtCore.SIGNAL(_fromUtf8("currentFontChanged(QFont)")), self.scoreView.setSectionFont)
        QtCore.QObject.connect(self.metadataFontCombo, QtCore.SIGNAL(_fromUtf8("currentFontChanged(QFont)")), self.scoreView.setMetadataFont)
        QtCore.QObject.connect(self.metadataFontSizeSpinbox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setMetadataFontSize)
        QtCore.QObject.connect(self.actionShowScoreInfo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.scoreView.setMetadataVisible)
        QtCore.QObject.connect(self.actionShowDrumKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.scoreView.setKitDataVisible)
        QtCore.QObject.connect(self.actionShowEmptyLines, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.scoreView.setEmptyLinesVisible)
        QtCore.QObject.connect(self.actionShowBeatCount, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.scoreView.setBeatCountVisible)
        QtCore.QObject.connect(self.actionShowScoreInfo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.metadataFontCombo.setEnabled)
        QtCore.QObject.connect(self.actionShowScoreInfo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.metadataFontSizeSpinbox.setEnabled)
        QtCore.QObject.connect(self.widthSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setWidth)
        QtCore.QObject.connect(self.lineSpaceSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.systemSpacingChanged)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("widthChanged(int)")), self.widthSpinBox.setValue)
        QtCore.QObject.connect(self.fontsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDisplayOptionsIsVisible.trigger)
        QtCore.QObject.connect(self.actionDisplayOptionsIsVisible, QtCore.SIGNAL(_fromUtf8("triggered()")), self.fontDock.raise_)
        QtCore.QObject.connect(self.sectionNavigator, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.scoreView.showSection)
        QtCore.QObject.connect(self.actionMIDIToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.MIDIToolBar.setVisible)
        QtCore.QObject.connect(self.MIDIToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionMIDIToolBarIsVisible.setChecked)
        QtCore.QMetaObject.connectSlotsByName(DrumBurpWindow)
        DrumBurpWindow.setTabOrder(self.paperBox, self.widthSpinBox)
        DrumBurpWindow.setTabOrder(self.widthSpinBox, self.lineSpaceSlider)
        DrumBurpWindow.setTabOrder(self.lineSpaceSlider, self.defaultMeasureButton)
        DrumBurpWindow.setTabOrder(self.defaultMeasureButton, self.fontsButton)
        DrumBurpWindow.setTabOrder(self.fontsButton, self.sectionNavigator)
        DrumBurpWindow.setTabOrder(self.sectionNavigator, self.scoreView)
        DrumBurpWindow.setTabOrder(self.scoreView, self.noteSizeSpinBox)
        DrumBurpWindow.setTabOrder(self.noteSizeSpinBox, self.fontComboBox)
        DrumBurpWindow.setTabOrder(self.fontComboBox, self.sectionFontCombo)
        DrumBurpWindow.setTabOrder(self.sectionFontCombo, self.sectionFontSizeSpinbox)
        DrumBurpWindow.setTabOrder(self.sectionFontSizeSpinbox, self.metadataFontCombo)
        DrumBurpWindow.setTabOrder(self.metadataFontCombo, self.metadataFontSizeSpinbox)

    def retranslateUi(self, DrumBurpWindow):
        DrumBurpWindow.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Score Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DrumBurpWindow", "Page Size", None, QtGui.QApplication.UnicodeUTF8))
        self.paperBox.setItemText(0, QtGui.QApplication.translate("DrumBurpWindow", "A4", None, QtGui.QApplication.UnicodeUTF8))
        self.paperBox.setItemText(1, QtGui.QApplication.translate("DrumBurpWindow", "Letter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DrumBurpWindow", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.widthSpinBox.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Score width", None, QtGui.QApplication.UnicodeUTF8))
        self.widthSpinBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The number of columns to display the Score on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DrumBurpWindow", "System Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpaceSlider.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Inter-system distance", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpaceSlider.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The distance between each system in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DrumBurpWindow", "Default Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultMeasureButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "MeasureCount", None, QtGui.QApplication.UnicodeUTF8))
        self.fontsButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fonts...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Operations on the DrumBurp Score", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Recently opened scores", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Open recently visited scores", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Recent Scores...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Options affecting the view", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShowToolBars.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Tool Bars...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fileToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.displayToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.exportToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Print && Export", None, QtGui.QApplication.UnicodeUTF8))
        self.helpToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fontDock.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Score Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.fontDock.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Set the fonts used to display the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.fontDock.setWhatsThis(QtGui.QApplication.translate("DrumBurpWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">There are 3 fonts used to display the Score, and they can be set in this dialog.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- The &quot;Note Font&quot; is used to display the notes themselves, the measure count, and any repeat indicators.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- The &quot;Section Title Font&quot; is used to display section titles.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- The &quot;Song Properties Font&quot; is used to display the song details, such as name, artist, etc.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fontDock.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Note Font", None, QtGui.QApplication.UnicodeUTF8))
        self.fontComboBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The font used to display notes in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.noteSizeSpinBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Size of notes.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Section Title Font", None, QtGui.QApplication.UnicodeUTF8))
        self.sectionFontCombo.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The font used to display section titles in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.sectionFontSizeSpinbox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Size of section titles.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties Font", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataFontCombo.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The font used to display section titles in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataFontSizeSpinbox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Size of section titles.", None, QtGui.QApplication.UnicodeUTF8))
        self.MIDIToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "MIDI ToolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DrumBurpWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DrumBurpWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setIconText(QtGui.QApplication.translate("DrumBurpWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "New Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Create a new blank score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("DrumBurpWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Open Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Load a saved DrumBurp score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Save this DrumBurp score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Save this DrumBurp score with a new name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setText(QtGui.QApplication.translate("DrumBurpWindow", "&Export ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Write an ASCII representation of this score to a file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setWhatsThis(QtGui.QApplication.translate("DrumBurpWindow", "Export this Score to an ASCII file.\n"
"\n"
"Writes this Score as a plain .txt file.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Choose Fonts...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of display options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of display options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of File tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitInWindow.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fit Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitInWindow.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Attempt to make the score as wide as possible within the current window.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbars.setText(QtGui.QApplication.translate("DrumBurpWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of Display tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("DrumBurpWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Print this Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setText(QtGui.QApplication.translate("DrumBurpWindow", "What\'s this?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Get help on DrumBurp elements", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Shift+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("DrumBurpWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Undo the last action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("DrumBurpWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Redo the last undone action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setText(QtGui.QApplication.translate("DrumBurpWindow", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Export this score to a PDF file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutDrumBurp.setText(QtGui.QApplication.translate("DrumBurpWindow", "About DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Print && Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of Print & Export Tool Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change the visibility of the Help Tool Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowEmptyLines.setText(QtGui.QApplication.translate("DrumBurpWindow", "Show Empty Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowEmptyLines.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Show or hide empty lines in the score.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDrumKey.setText(QtGui.QApplication.translate("DrumBurpWindow", "Show Drum Key", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDrumKey.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Show Drum Key", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowScoreInfo.setText(QtGui.QApplication.translate("DrumBurpWindow", "Show Score Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowBeatCount.setText(QtGui.QApplication.translate("DrumBurpWindow", "Show Beat Count", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitPage.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fit Page...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitPage.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Fit Score to Page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayScore.setText(QtGui.QApplication.translate("DrumBurpWindow", "Play Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayScore.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Play this score through MIDI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMuteNotes.setText(QtGui.QApplication.translate("DrumBurpWindow", "Mute Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMuteNotes.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Enable/disable note audio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportMIDI.setText(QtGui.QApplication.translate("DrumBurpWindow", "Export MIDI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportMIDI.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Export this score to a MIDI file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMIDIToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "MIDI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMIDIToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of MIDI toolbar", None, QtGui.QApplication.UnicodeUTF8))

from Widgets.ScoreView_plugin import ScoreView
import DrumBurp_rc
