# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\DrumBurp\src\GUI\drumburp.ui'
#
# Created: Tue Mar 08 23:07:52 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DrumBurpWindow(object):
    def setupUi(self, DrumBurpWindow):
        DrumBurpWindow.setObjectName(_fromUtf8("DrumBurpWindow"))
        DrumBurpWindow.resize(800, 668)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/drumburp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DrumBurpWindow.setWindowIcon(icon)
        DrumBurpWindow.setAnimated(True)
        DrumBurpWindow.setDockNestingEnabled(True)
        DrumBurpWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(DrumBurpWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scoreView = ScoreView(self.centralwidget)
        self.scoreView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scoreView.setAcceptDrops(False)
        self.scoreView.setLineWidth(1)
        self.scoreView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.scoreView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.scoreView.setObjectName(_fromUtf8("scoreView"))
        self.gridLayout_2.addWidget(self.scoreView, 0, 0, 1, 1)
        DrumBurpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DrumBurpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecentScores = QtGui.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRecentScores.setIcon(icon1)
        self.menuRecentScores.setObjectName(_fromUtf8("menuRecentScores"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShow = QtGui.QMenu(self.menuView)
        self.menuShow.setObjectName(_fromUtf8("menuShow"))
        self.menuShowToolBars = QtGui.QMenu(self.menuView)
        self.menuShowToolBars.setObjectName(_fromUtf8("menuShowToolBars"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        DrumBurpWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DrumBurpWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DrumBurpWindow.setStatusBar(self.statusbar)
        self.fileToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.fileToolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fileToolBar.setMovable(True)
        self.fileToolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.fileToolBar.setIconSize(QtCore.QSize(32, 32))
        self.fileToolBar.setObjectName(_fromUtf8("fileToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolBar)
        self.noteHeadDock = QtGui.QDockWidget(DrumBurpWindow)
        self.noteHeadDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.noteHeadDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.noteHeadDock.setObjectName(_fromUtf8("noteHeadDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.defaultNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.defaultNoteHeadButton.setChecked(True)
        self.defaultNoteHeadButton.setObjectName(_fromUtf8("defaultNoteHeadButton"))
        self.gridLayout.addWidget(self.defaultNoteHeadButton, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.bigXNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.bigXNoteHeadButton.setObjectName(_fromUtf8("bigXNoteHeadButton"))
        self.gridLayout.addWidget(self.bigXNoteHeadButton, 3, 1, 1, 1)
        self.xNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.xNoteHeadButton.setObjectName(_fromUtf8("xNoteHeadButton"))
        self.gridLayout.addWidget(self.xNoteHeadButton, 3, 0, 1, 1)
        self.bigONoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.bigONoteHeadButton.setObjectName(_fromUtf8("bigONoteHeadButton"))
        self.gridLayout.addWidget(self.bigONoteHeadButton, 5, 1, 1, 1)
        self.oNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.oNoteHeadButton.setObjectName(_fromUtf8("oNoteHeadButton"))
        self.gridLayout.addWidget(self.oNoteHeadButton, 5, 0, 1, 1)
        self.gNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.gNoteHeadButton.setObjectName(_fromUtf8("gNoteHeadButton"))
        self.gridLayout.addWidget(self.gNoteHeadButton, 3, 2, 1, 1)
        self.flamNoteTeller = RadioButtonTeller(self.dockWidgetContents)
        self.flamNoteTeller.setObjectName(_fromUtf8("flamNoteTeller"))
        self.gridLayout.addWidget(self.flamNoteTeller, 5, 2, 1, 1)
        self.plusNoteHeadButton = RadioButtonTeller(self.dockWidgetContents)
        self.plusNoteHeadButton.setObjectName(_fromUtf8("plusNoteHeadButton"))
        self.gridLayout.addWidget(self.plusNoteHeadButton, 6, 0, 1, 1)
        self.dragNoteTeller = RadioButtonTeller(self.dockWidgetContents)
        self.dragNoteTeller.setObjectName(_fromUtf8("dragNoteTeller"))
        self.gridLayout.addWidget(self.dragNoteTeller, 6, 2, 1, 1)
        self.noteHeadDock.setWidget(self.dockWidgetContents)
        DrumBurpWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.noteHeadDock)
        self.diplayOptionsDock = QtGui.QDockWidget(DrumBurpWindow)
        self.diplayOptionsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.diplayOptionsDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.diplayOptionsDock.setObjectName(_fromUtf8("diplayOptionsDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_2.setToolTip(_fromUtf8(""))
        self.label_2.setStatusTip(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.lineSpaceSlider = QtGui.QSlider(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSpaceSlider.sizePolicy().hasHeightForWidth())
        self.lineSpaceSlider.setSizePolicy(sizePolicy)
        self.lineSpaceSlider.setMaximum(100)
        self.lineSpaceSlider.setTracking(False)
        self.lineSpaceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lineSpaceSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.lineSpaceSlider.setObjectName(_fromUtf8("lineSpaceSlider"))
        self.verticalLayout.addWidget(self.lineSpaceSlider)
        self.widthLabel = QtGui.QLabel(self.dockWidgetContents_2)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.verticalLayout.addWidget(self.widthLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.fontComboBox = QtGui.QFontComboBox(self.dockWidgetContents_2)
        self.fontComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.fontComboBox.setMaximumSize(QtCore.QSize(187, 20))
        self.fontComboBox.setEditable(False)
        self.fontComboBox.setMaxVisibleItems(20)
        self.fontComboBox.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("BatangChe"))
        font.setPointSize(10)
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.horizontalLayout_5.addWidget(self.fontComboBox)
        self.noteSizeSpinBox = QtGui.QSpinBox(self.dockWidgetContents_2)
        self.noteSizeSpinBox.setMinimum(6)
        self.noteSizeSpinBox.setMaximum(30)
        self.noteSizeSpinBox.setProperty(_fromUtf8("value"), 10)
        self.noteSizeSpinBox.setObjectName(_fromUtf8("noteSizeSpinBox"))
        self.horizontalLayout_5.addWidget(self.noteSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.sectionFontCombo = QtGui.QFontComboBox(self.dockWidgetContents_2)
        self.sectionFontCombo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionFontCombo.sizePolicy().hasHeightForWidth())
        self.sectionFontCombo.setSizePolicy(sizePolicy)
        self.sectionFontCombo.setMinimumSize(QtCore.QSize(100, 20))
        self.sectionFontCombo.setMaximumSize(QtCore.QSize(187, 20))
        self.sectionFontCombo.setEditable(False)
        self.sectionFontCombo.setMaxVisibleItems(20)
        self.sectionFontCombo.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("BatangChe"))
        font.setPointSize(10)
        self.sectionFontCombo.setCurrentFont(font)
        self.sectionFontCombo.setObjectName(_fromUtf8("sectionFontCombo"))
        self.horizontalLayout_4.addWidget(self.sectionFontCombo)
        self.sectionFontSizeSpinbox = QtGui.QSpinBox(self.dockWidgetContents_2)
        self.sectionFontSizeSpinbox.setMinimum(8)
        self.sectionFontSizeSpinbox.setMaximum(48)
        self.sectionFontSizeSpinbox.setProperty(_fromUtf8("value"), 20)
        self.sectionFontSizeSpinbox.setObjectName(_fromUtf8("sectionFontSizeSpinbox"))
        self.horizontalLayout_4.addWidget(self.sectionFontSizeSpinbox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.beatsSpinBox = QtGui.QSpinBox(self.dockWidgetContents_2)
        self.beatsSpinBox.setMinimum(1)
        self.beatsSpinBox.setMaximum(256)
        self.beatsSpinBox.setProperty(_fromUtf8("value"), 4)
        self.beatsSpinBox.setObjectName(_fromUtf8("beatsSpinBox"))
        self.horizontalLayout.addWidget(self.beatsSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.beatCountComboBox = QtGui.QComboBox(self.dockWidgetContents_2)
        self.beatCountComboBox.setMaxCount(20)
        self.beatCountComboBox.setObjectName(_fromUtf8("beatCountComboBox"))
        self.horizontalLayout_3.addWidget(self.beatCountComboBox)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.diplayOptionsDock.setWidget(self.dockWidgetContents_2)
        DrumBurpWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.diplayOptionsDock)
        self.songPropertiesDock = QtGui.QDockWidget(DrumBurpWindow)
        self.songPropertiesDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.songPropertiesDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.songPropertiesDock.setObjectName(_fromUtf8("songPropertiesDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.songNameLabel = QtGui.QLabel(self.dockWidgetContents_3)
        self.songNameLabel.setObjectName(_fromUtf8("songNameLabel"))
        self.gridLayout_3.addWidget(self.songNameLabel, 1, 0, 1, 1)
        self.songNameEdit = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.songNameEdit.setObjectName(_fromUtf8("songNameEdit"))
        self.gridLayout_3.addWidget(self.songNameEdit, 1, 1, 1, 1)
        self.bpmLabel = QtGui.QLabel(self.dockWidgetContents_3)
        self.bpmLabel.setObjectName(_fromUtf8("bpmLabel"))
        self.gridLayout_3.addWidget(self.bpmLabel, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bpmSpinBox = QtGui.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpmSpinBox.sizePolicy().hasHeightForWidth())
        self.bpmSpinBox.setSizePolicy(sizePolicy)
        self.bpmSpinBox.setFrame(True)
        self.bpmSpinBox.setMaximum(300)
        self.bpmSpinBox.setProperty(_fromUtf8("value"), 120)
        self.bpmSpinBox.setObjectName(_fromUtf8("bpmSpinBox"))
        self.horizontalLayout_2.addWidget(self.bpmSpinBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.widthSpinBox = QtGui.QSpinBox(self.dockWidgetContents_3)
        self.widthSpinBox.setMinimum(10)
        self.widthSpinBox.setMaximum(1000)
        self.widthSpinBox.setProperty(_fromUtf8("value"), 80)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.horizontalLayout_2.addWidget(self.widthSpinBox)
        self.fitWindowButton = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitWindowButton.sizePolicy().hasHeightForWidth())
        self.fitWindowButton.setSizePolicy(sizePolicy)
        self.fitWindowButton.setObjectName(_fromUtf8("fitWindowButton"))
        self.horizontalLayout_2.addWidget(self.fitWindowButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        self.tabberEdit = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.tabberEdit.setObjectName(_fromUtf8("tabberEdit"))
        self.gridLayout_3.addWidget(self.tabberEdit, 3, 1, 1, 1)
        self.artistNameEdit = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.artistNameEdit.setObjectName(_fromUtf8("artistNameEdit"))
        self.gridLayout_3.addWidget(self.artistNameEdit, 1, 3, 1, 1)
        self.artistNameLabel = QtGui.QLabel(self.dockWidgetContents_3)
        self.artistNameLabel.setObjectName(_fromUtf8("artistNameLabel"))
        self.gridLayout_3.addWidget(self.artistNameLabel, 1, 2, 1, 1)
        self.tabberLabel = QtGui.QLabel(self.dockWidgetContents_3)
        self.tabberLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.tabberLabel.setObjectName(_fromUtf8("tabberLabel"))
        self.gridLayout_3.addWidget(self.tabberLabel, 3, 0, 1, 1)
        self.songPropertiesDock.setWidget(self.dockWidgetContents_3)
        DrumBurpWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.songPropertiesDock)
        self.displayToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.displayToolBar.setMovable(True)
        self.displayToolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.displayToolBar.setObjectName(_fromUtf8("displayToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.displayToolBar)
        self.exportToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.exportToolBar.setObjectName(_fromUtf8("exportToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.exportToolBar)
        self.helpToolBar = QtGui.QToolBar(DrumBurpWindow)
        self.helpToolBar.setObjectName(_fromUtf8("helpToolBar"))
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.helpToolBar)
        self.actionQuit = QtGui.QAction(DrumBurpWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/system-log-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew = QtGui.QAction(DrumBurpWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionLoad = QtGui.QAction(DrumBurpWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon4)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(DrumBurpWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(DrumBurpWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon6)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionExportASCII = QtGui.QAction(DrumBurpWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/format-text-bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportASCII.setIcon(icon7)
        self.actionExportASCII.setObjectName(_fromUtf8("actionExportASCII"))
        self.actionDisplayOptionsIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionDisplayOptionsIsVisible.setCheckable(True)
        self.actionDisplayOptionsIsVisible.setObjectName(_fromUtf8("actionDisplayOptionsIsVisible"))
        self.actionSongPropertiesIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionSongPropertiesIsVisible.setCheckable(True)
        self.actionSongPropertiesIsVisible.setObjectName(_fromUtf8("actionSongPropertiesIsVisible"))
        self.actionNoteHeadSelectorIsVisble = QtGui.QAction(DrumBurpWindow)
        self.actionNoteHeadSelectorIsVisble.setCheckable(True)
        self.actionNoteHeadSelectorIsVisble.setObjectName(_fromUtf8("actionNoteHeadSelectorIsVisble"))
        self.actionFileToolbarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionFileToolbarIsVisible.setCheckable(True)
        self.actionFileToolbarIsVisible.setObjectName(_fromUtf8("actionFileToolbarIsVisible"))
        self.actionFitInWindow = QtGui.QAction(DrumBurpWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/format-justify-fill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFitInWindow.setIcon(icon8)
        self.actionFitInWindow.setObjectName(_fromUtf8("actionFitInWindow"))
        self.actionToolbars = QtGui.QAction(DrumBurpWindow)
        self.actionToolbars.setObjectName(_fromUtf8("actionToolbars"))
        self.actionDisplayToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionDisplayToolBarIsVisible.setCheckable(True)
        self.actionDisplayToolBarIsVisible.setObjectName(_fromUtf8("actionDisplayToolBarIsVisible"))
        self.actionPrint = QtGui.QAction(DrumBurpWindow)
        self.actionPrint.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon9)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionWhatsThis = QtGui.QAction(DrumBurpWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/help-browser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWhatsThis.setIcon(icon10)
        self.actionWhatsThis.setObjectName(_fromUtf8("actionWhatsThis"))
        self.actionUndo = QtGui.QAction(DrumBurpWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(DrumBurpWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionExportPDF = QtGui.QAction(DrumBurpWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportPDF.setIcon(icon11)
        self.actionExportPDF.setObjectName(_fromUtf8("actionExportPDF"))
        self.actionAbout_DrumBurp = QtGui.QAction(DrumBurpWindow)
        self.actionAbout_DrumBurp.setObjectName(_fromUtf8("actionAbout_DrumBurp"))
        self.actionExportToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionExportToolBarIsVisible.setCheckable(True)
        self.actionExportToolBarIsVisible.setObjectName(_fromUtf8("actionExportToolBarIsVisible"))
        self.actionHelpToolBarIsVisible = QtGui.QAction(DrumBurpWindow)
        self.actionHelpToolBarIsVisible.setCheckable(True)
        self.actionHelpToolBarIsVisible.setObjectName(_fromUtf8("actionHelpToolBarIsVisible"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.menuRecentScores.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExportASCII)
        self.menuFile.addAction(self.actionExportPDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuShow.addAction(self.actionDisplayOptionsIsVisible)
        self.menuShow.addAction(self.actionSongPropertiesIsVisible)
        self.menuShow.addAction(self.actionNoteHeadSelectorIsVisble)
        self.menuShowToolBars.addAction(self.actionFileToolbarIsVisible)
        self.menuShowToolBars.addAction(self.actionDisplayToolBarIsVisible)
        self.menuShowToolBars.addAction(self.actionExportToolBarIsVisible)
        self.menuShowToolBars.addAction(self.actionHelpToolBarIsVisible)
        self.menuView.addAction(self.actionFitInWindow)
        self.menuView.addAction(self.menuShow.menuAction())
        self.menuView.addAction(self.menuShowToolBars.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionWhatsThis)
        self.menuHelp.addAction(self.actionAbout_DrumBurp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.fileToolBar.addAction(self.actionNew)
        self.fileToolBar.addAction(self.actionLoad)
        self.fileToolBar.addAction(self.actionSave)
        self.fileToolBar.addAction(self.actionSaveAs)
        self.displayToolBar.addAction(self.actionFitInWindow)
        self.exportToolBar.addAction(self.actionPrint)
        self.exportToolBar.addAction(self.actionExportASCII)
        self.exportToolBar.addAction(self.actionExportPDF)
        self.helpToolBar.addAction(self.actionWhatsThis)
        self.label_2.setBuddy(self.lineSpaceSlider)
        self.widthLabel.setBuddy(self.fontComboBox)
        self.songNameLabel.setBuddy(self.songNameEdit)
        self.bpmLabel.setBuddy(self.bpmSpinBox)
        self.label_3.setBuddy(self.widthSpinBox)
        self.artistNameLabel.setBuddy(self.artistNameEdit)
        self.tabberLabel.setBuddy(self.tabberEdit)

        self.retranslateUi(DrumBurpWindow)
        QtCore.QObject.connect(self.defaultNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.xNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.bigXNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.oNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.bigONoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.plusNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.gNoteHeadButton, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.lineSpaceSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.systemSpacingChanged)
        QtCore.QObject.connect(self.fontComboBox, QtCore.SIGNAL(_fromUtf8("currentFontChanged(QFont)")), self.scoreView.setFont)
        QtCore.QObject.connect(self.actionDisplayOptionsIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.diplayOptionsDock.setVisible)
        QtCore.QObject.connect(self.actionNoteHeadSelectorIsVisble, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.noteHeadDock.setVisible)
        QtCore.QObject.connect(self.actionSongPropertiesIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.songPropertiesDock.setVisible)
        QtCore.QObject.connect(self.songPropertiesDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionSongPropertiesIsVisible.setChecked)
        QtCore.QObject.connect(self.noteHeadDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionNoteHeadSelectorIsVisble.setChecked)
        QtCore.QObject.connect(self.diplayOptionsDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDisplayOptionsIsVisible.setChecked)
        QtCore.QObject.connect(self.actionFileToolbarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fileToolBar.setVisible)
        QtCore.QObject.connect(self.fileToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionFileToolbarIsVisible.setChecked)
        QtCore.QObject.connect(self.widthSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setWidth)
        QtCore.QObject.connect(self.fitWindowButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFitInWindow.trigger)
        QtCore.QObject.connect(self.displayToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDisplayToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.actionDisplayToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.displayToolBar.setVisible)
        QtCore.QObject.connect(self.beatsSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setDefaultMeasureWidth)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), DrumBurpWindow.close)
        QtCore.QObject.connect(self.flamNoteTeller, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.dragNoteTeller, QtCore.SIGNAL(_fromUtf8("emitValue(QString)")), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("widthChanged(int)")), self.widthSpinBox.setValue)
        QtCore.QObject.connect(self.bpmSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setBPM)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("bpmChanged(int)")), self.bpmSpinBox.setValue)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("artistChanged(QString)")), self.artistNameEdit.setText)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("titleChanged(QString)")), self.songNameEdit.setText)
        QtCore.QObject.connect(self.scoreView, QtCore.SIGNAL(_fromUtf8("creatorChanged(QString)")), self.tabberEdit.setText)
        QtCore.QObject.connect(self.sectionFontCombo, QtCore.SIGNAL(_fromUtf8("currentFontChanged(QFont)")), self.scoreView.setSectionFont)
        QtCore.QObject.connect(self.sectionFontSizeSpinbox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setSectionFontSize)
        QtCore.QObject.connect(self.actionExportToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.exportToolBar.setVisible)
        QtCore.QObject.connect(self.exportToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionExportToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.actionHelpToolBarIsVisible, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.helpToolBar.setVisible)
        QtCore.QObject.connect(self.helpToolBar, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionHelpToolBarIsVisible.setChecked)
        QtCore.QObject.connect(self.noteSizeSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scoreView.setNoteFontSize)
        QtCore.QMetaObject.connectSlotsByName(DrumBurpWindow)
        DrumBurpWindow.setTabOrder(self.songNameEdit, self.artistNameEdit)
        DrumBurpWindow.setTabOrder(self.artistNameEdit, self.tabberEdit)
        DrumBurpWindow.setTabOrder(self.tabberEdit, self.bpmSpinBox)
        DrumBurpWindow.setTabOrder(self.bpmSpinBox, self.widthSpinBox)
        DrumBurpWindow.setTabOrder(self.widthSpinBox, self.fitWindowButton)
        DrumBurpWindow.setTabOrder(self.fitWindowButton, self.lineSpaceSlider)
        DrumBurpWindow.setTabOrder(self.lineSpaceSlider, self.fontComboBox)
        DrumBurpWindow.setTabOrder(self.fontComboBox, self.beatsSpinBox)
        DrumBurpWindow.setTabOrder(self.beatsSpinBox, self.beatCountComboBox)
        DrumBurpWindow.setTabOrder(self.beatCountComboBox, self.defaultNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.defaultNoteHeadButton, self.xNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.xNoteHeadButton, self.bigXNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.bigXNoteHeadButton, self.gNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.gNoteHeadButton, self.oNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.oNoteHeadButton, self.bigONoteHeadButton)
        DrumBurpWindow.setTabOrder(self.bigONoteHeadButton, self.flamNoteTeller)
        DrumBurpWindow.setTabOrder(self.flamNoteTeller, self.plusNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.plusNoteHeadButton, self.dragNoteTeller)
        DrumBurpWindow.setTabOrder(self.dragNoteTeller, self.scoreView)

    def retranslateUi(self, DrumBurpWindow):
        DrumBurpWindow.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Operations on the DrumBurp Score", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Recently opened scores", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Open recently visited scores", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentScores.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Recent Scores...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Options affecting the view", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShow.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Select visible components", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShow.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Show...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShowToolBars.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Show Tool Bars...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fileToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.noteHeadDock.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Select the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.noteHeadDock.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The note head determines what note will be placed in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.noteHeadDock.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Note Head", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Default note head", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use the default note head for each instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "X note head", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"X\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "x note head", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"x\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "O note head", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"O\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "o note head", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"o\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "g note head", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"g\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "g", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "g", None, QtGui.QApplication.UnicodeUTF8))
        self.flamNoteTeller.setText(QtGui.QApplication.translate("DrumBurpWindow", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "+ note head", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Use \"+\" as the note head", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setProperty(_fromUtf8("buttonValue"), QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.dragNoteTeller.setText(QtGui.QApplication.translate("DrumBurpWindow", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.diplayOptionsDock.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Display Options", None, QtGui.QApplication.UnicodeUTF8))
        self.diplayOptionsDock.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Options affecting how the Score is displayed", None, QtGui.QApplication.UnicodeUTF8))
        self.diplayOptionsDock.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Display Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DrumBurpWindow", "System Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpaceSlider.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Inter-system distance", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpaceSlider.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The distance between each system in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Note font", None, QtGui.QApplication.UnicodeUTF8))
        self.fontComboBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The font used to display notes in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DrumBurpWindow", "Section Title font", None, QtGui.QApplication.UnicodeUTF8))
        self.sectionFontCombo.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The font used to display notes in the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DrumBurpWindow", "Default Measure Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DrumBurpWindow", "Beats per measure", None, QtGui.QApplication.UnicodeUTF8))
        self.beatsSpinBox.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Default Measure Width", None, QtGui.QApplication.UnicodeUTF8))
        self.beatsSpinBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The number of ticks in default measures added to the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.beatsSpinBox.setSuffix(QtGui.QApplication.translate("DrumBurpWindow", " beats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DrumBurpWindow", "Beat count", None, QtGui.QApplication.UnicodeUTF8))
        self.songPropertiesDock.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.songPropertiesDock.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Information about the Score", None, QtGui.QApplication.UnicodeUTF8))
        self.songPropertiesDock.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.songNameLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.songNameEdit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Song name", None, QtGui.QApplication.UnicodeUTF8))
        self.songNameEdit.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Song name", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "&BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmSpinBox.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmSpinBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Beats per minute", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmSpinBox.setSuffix(QtGui.QApplication.translate("DrumBurpWindow", " bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DrumBurpWindow", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.widthSpinBox.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Score width", None, QtGui.QApplication.UnicodeUTF8))
        self.widthSpinBox.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "The number of columns to display the Score on", None, QtGui.QApplication.UnicodeUTF8))
        self.fitWindowButton.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Fit Score In Window", None, QtGui.QApplication.UnicodeUTF8))
        self.fitWindowButton.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Attempt to make the score as wide as possible within the current window.", None, QtGui.QApplication.UnicodeUTF8))
        self.fitWindowButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fit Window", None, QtGui.QApplication.UnicodeUTF8))
        self.tabberEdit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Score creator", None, QtGui.QApplication.UnicodeUTF8))
        self.tabberEdit.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Who created this DrumBurp score", None, QtGui.QApplication.UnicodeUTF8))
        self.artistNameEdit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Song artist", None, QtGui.QApplication.UnicodeUTF8))
        self.artistNameEdit.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Song artist", None, QtGui.QApplication.UnicodeUTF8))
        self.artistNameLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "&Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.tabberLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Tabbed by", None, QtGui.QApplication.UnicodeUTF8))
        self.displayToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.exportToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Print && Export", None, QtGui.QApplication.UnicodeUTF8))
        self.helpToolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DrumBurpWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DrumBurpWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setIconText(QtGui.QApplication.translate("DrumBurpWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "New Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Create a new blank score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("DrumBurpWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Open Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Load a saved DrumBurp score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Save this DrumBurp score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Save this DrumBurp score with a new name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setText(QtGui.QApplication.translate("DrumBurpWindow", "&Export ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Write an ASCII representation of this score to a file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setWhatsThis(QtGui.QApplication.translate("DrumBurpWindow", "Export this Score to an ASCII file.\n"
"\n"
"Writes this Score as a plain .txt file.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportASCII.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Display Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of display options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayOptionsIsVisible.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of display options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSongPropertiesIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSongPropertiesIsVisible.setIconText(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of song properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSongPropertiesIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of song properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoteHeadSelectorIsVisble.setText(QtGui.QApplication.translate("DrumBurpWindow", "Note Head Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoteHeadSelectorIsVisble.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of note head selector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoteHeadSelectorIsVisble.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of note head selector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of File tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileToolbarIsVisible.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitInWindow.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fit Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitInWindow.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Attempt to make the score as wide as possible within the current window.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbars.setText(QtGui.QApplication.translate("DrumBurpWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisplayToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of Display tool bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("DrumBurpWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Print this Score", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setText(QtGui.QApplication.translate("DrumBurpWindow", "What\'s this?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Get help on DrumBurp elements", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhatsThis.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Shift+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("DrumBurpWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Undo the last action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("DrumBurpWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Redo the last undone action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("DrumBurpWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setText(QtGui.QApplication.translate("DrumBurpWindow", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setStatusTip(QtGui.QApplication.translate("DrumBurpWindow", "Export this score to a PDF file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_DrumBurp.setText(QtGui.QApplication.translate("DrumBurpWindow", "About DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Print && Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change visibility of Print & Export Tool Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpToolBarIsVisible.setText(QtGui.QApplication.translate("DrumBurpWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpToolBarIsVisible.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Change the visibility of the Help Tool Bar", None, QtGui.QApplication.UnicodeUTF8))

from Widgets.ScoreView_plugin import ScoreView
from Widgets.RadioButtonTeller_plugin import RadioButtonTeller
import DrumBurp_rc
