# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike\workspace\DrumBurp\src\GUI\editKit.ui'
#
# Created: Sat Mar 03 22:59:54 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_editKitDialog(object):
    def setupUi(self, editKitDialog):
        editKitDialog.setObjectName(_fromUtf8("editKitDialog"))
        editKitDialog.resize(848, 440)
        editKitDialog.setWindowTitle(QtGui.QApplication.translate("editKitDialog", "Edit Drum Kit", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_10 = QtGui.QVBoxLayout(editKitDialog)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(editKitDialog)
        self.groupBox_5.setToolTip(QtGui.QApplication.translate("editKitDialog", "The drums in the kit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("editKitDialog", "Drums", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.kitTable = QtGui.QListWidget(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kitTable.sizePolicy().hasHeightForWidth())
        self.kitTable.setSizePolicy(sizePolicy)
        self.kitTable.setMinimumSize(QtCore.QSize(256, 0))
        self.kitTable.setToolTip(QtGui.QApplication.translate("editKitDialog", "The drums and their order", None, QtGui.QApplication.UnicodeUTF8))
        self.kitTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.kitTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.kitTable.setObjectName(_fromUtf8("kitTable"))
        self.verticalLayout_2.addWidget(self.kitTable)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.addButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(24, 24))
        self.addButton.setMaximumSize(QtCore.QSize(24, 24))
        self.addButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Add a drum", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/GUI/Icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.horizontalLayout_5.addWidget(self.addButton)
        self.upButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setMinimumSize(QtCore.QSize(24, 24))
        self.upButton.setMaximumSize(QtCore.QSize(24, 24))
        self.upButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Move the current drum up", None, QtGui.QApplication.UnicodeUTF8))
        self.upButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/GUI/Icons/go-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon1)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.horizontalLayout_5.addWidget(self.upButton)
        self.downButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setMinimumSize(QtCore.QSize(24, 24))
        self.downButton.setMaximumSize(QtCore.QSize(24, 24))
        self.downButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Move the current drum down", None, QtGui.QApplication.UnicodeUTF8))
        self.downButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/GUI/Icons/go-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon2)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.horizontalLayout_5.addWidget(self.downButton)
        self.deleteButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setMinimumSize(QtCore.QSize(24, 24))
        self.deleteButton.setMaximumSize(QtCore.QSize(24, 24))
        self.deleteButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Remove the current drum", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/GUI/Icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_5.addWidget(self.deleteButton)
        self.clearButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(24, 24))
        self.clearButton.setMaximumSize(QtCore.QSize(24, 24))
        self.clearButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Clear the kit and start again", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon4)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.resetButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(24, 24))
        self.resetButton.setMaximumSize(QtCore.QSize(24, 24))
        self.resetButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Reset the kit", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon5)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout_5.addWidget(self.resetButton)
        self.deleteEmptyButton = QtGui.QPushButton(self.groupBox_5)
        self.deleteEmptyButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteEmptyButton.sizePolicy().hasHeightForWidth())
        self.deleteEmptyButton.setSizePolicy(sizePolicy)
        self.deleteEmptyButton.setMinimumSize(QtCore.QSize(24, 24))
        self.deleteEmptyButton.setMaximumSize(QtCore.QSize(24, 24))
        self.deleteEmptyButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Delete empty non-locked drums", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEmptyButton.setStatusTip(_fromUtf8(""))
        self.deleteEmptyButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/process-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteEmptyButton.setIcon(icon6)
        self.deleteEmptyButton.setObjectName(_fromUtf8("deleteEmptyButton"))
        self.horizontalLayout_5.addWidget(self.deleteEmptyButton)
        self.loadButton = QtGui.QPushButton(self.groupBox_5)
        self.loadButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMinimumSize(QtCore.QSize(24, 24))
        self.loadButton.setMaximumSize(QtCore.QSize(24, 24))
        self.loadButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Load a drum kit", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadButton.setIcon(icon7)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.horizontalLayout_5.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.groupBox_5)
        self.saveButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(24, 24))
        self.saveButton.setMaximumSize(QtCore.QSize(24, 24))
        self.saveButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Save this drum kit", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon8)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_5.addWidget(self.saveButton)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.line_2 = QtGui.QFrame(editKitDialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        spacerItem3 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_6 = QtGui.QGroupBox(editKitDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setToolTip(QtGui.QApplication.translate("editKitDialog", "Identifying information for the drum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("editKitDialog", "Drum Info", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setToolTip(QtGui.QApplication.translate("editKitDialog", "Name for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("editKitDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.drumName = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumName.sizePolicy().hasHeightForWidth())
        self.drumName.setSizePolicy(sizePolicy)
        self.drumName.setMinimumSize(QtCore.QSize(143, 0))
        self.drumName.setToolTip(QtGui.QApplication.translate("editKitDialog", "Name for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.drumName.setObjectName(_fromUtf8("drumName"))
        self.gridLayout_2.addWidget(self.drumName, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText(QtGui.QApplication.translate("editKitDialog", "Abbreviation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.drumAbbr = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drumAbbr.sizePolicy().hasHeightForWidth())
        self.drumAbbr.setSizePolicy(sizePolicy)
        self.drumAbbr.setMinimumSize(QtCore.QSize(143, 0))
        self.drumAbbr.setToolTip(QtGui.QApplication.translate("editKitDialog", "Abbreviation for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.drumAbbr.setStatusTip(QtGui.QApplication.translate("editKitDialog", "Abbreviation for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.drumAbbr.setInputMask(QtGui.QApplication.translate("editKitDialog", "NN; ", None, QtGui.QApplication.UnicodeUTF8))
        self.drumAbbr.setMaxLength(2)
        self.drumAbbr.setObjectName(_fromUtf8("drumAbbr"))
        self.gridLayout_2.addWidget(self.drumAbbr, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setToolTip(QtGui.QApplication.translate("editKitDialog", "Copy the data from one of the drums in the current score to this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("editKitDialog", "Convert from existing drum?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.oldDrum = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldDrum.sizePolicy().hasHeightForWidth())
        self.oldDrum.setSizePolicy(sizePolicy)
        self.oldDrum.setMinimumSize(QtCore.QSize(143, 0))
        self.oldDrum.setToolTip(QtGui.QApplication.translate("editKitDialog", "Copy the data from one of the drums in the current score to this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.oldDrum.setObjectName(_fromUtf8("oldDrum"))
        self.gridLayout_2.addWidget(self.oldDrum, 2, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(editKitDialog)
        self.groupBox.setToolTip(QtGui.QApplication.translate("editKitDialog", "Define the valid note heads for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("editKitDialog", "Note Heads", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setText(QtGui.QApplication.translate("editKitDialog", "Current note head", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.currentNoteHead = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentNoteHead.sizePolicy().hasHeightForWidth())
        self.currentNoteHead.setSizePolicy(sizePolicy)
        self.currentNoteHead.setToolTip(QtGui.QApplication.translate("editKitDialog", "Change the selected note head", None, QtGui.QApplication.UnicodeUTF8))
        self.currentNoteHead.setObjectName(_fromUtf8("currentNoteHead"))
        self.horizontalLayout_4.addWidget(self.currentNoteHead)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.noteHeadTable = QtGui.QListWidget(self.groupBox)
        self.noteHeadTable.setMinimumSize(QtCore.QSize(214, 177))
        self.noteHeadTable.setToolTip(QtGui.QApplication.translate("editKitDialog", "A list of the valid note heads for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.noteHeadTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.noteHeadTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.noteHeadTable.setProperty("showDropIndicator", False)
        self.noteHeadTable.setObjectName(_fromUtf8("noteHeadTable"))
        self.verticalLayout.addWidget(self.noteHeadTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.addHeadButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHeadButton.sizePolicy().hasHeightForWidth())
        self.addHeadButton.setSizePolicy(sizePolicy)
        self.addHeadButton.setMinimumSize(QtCore.QSize(28, 24))
        self.addHeadButton.setMaximumSize(QtCore.QSize(28, 24))
        self.addHeadButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Add a new note head for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.addHeadButton.setText(_fromUtf8(""))
        self.addHeadButton.setIcon(icon)
        self.addHeadButton.setObjectName(_fromUtf8("addHeadButton"))
        self.horizontalLayout.addWidget(self.addHeadButton)
        self.headUpButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headUpButton.sizePolicy().hasHeightForWidth())
        self.headUpButton.setSizePolicy(sizePolicy)
        self.headUpButton.setMinimumSize(QtCore.QSize(28, 24))
        self.headUpButton.setMaximumSize(QtCore.QSize(28, 24))
        self.headUpButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Move the current note head up", None, QtGui.QApplication.UnicodeUTF8))
        self.headUpButton.setIcon(icon1)
        self.headUpButton.setObjectName(_fromUtf8("headUpButton"))
        self.horizontalLayout.addWidget(self.headUpButton)
        self.setDefaultHeadButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setDefaultHeadButton.sizePolicy().hasHeightForWidth())
        self.setDefaultHeadButton.setSizePolicy(sizePolicy)
        self.setDefaultHeadButton.setMinimumSize(QtCore.QSize(75, 23))
        self.setDefaultHeadButton.setMaximumSize(QtCore.QSize(75, 23))
        self.setDefaultHeadButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Make the currently selected note head the default for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.setDefaultHeadButton.setText(QtGui.QApplication.translate("editKitDialog", "Set Default", None, QtGui.QApplication.UnicodeUTF8))
        self.setDefaultHeadButton.setObjectName(_fromUtf8("setDefaultHeadButton"))
        self.horizontalLayout.addWidget(self.setDefaultHeadButton)
        self.headDownButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headDownButton.sizePolicy().hasHeightForWidth())
        self.headDownButton.setSizePolicy(sizePolicy)
        self.headDownButton.setMinimumSize(QtCore.QSize(28, 24))
        self.headDownButton.setMaximumSize(QtCore.QSize(28, 24))
        self.headDownButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Move the current note head down", None, QtGui.QApplication.UnicodeUTF8))
        self.headDownButton.setText(_fromUtf8(""))
        self.headDownButton.setIcon(icon2)
        self.headDownButton.setObjectName(_fromUtf8("headDownButton"))
        self.horizontalLayout.addWidget(self.headDownButton)
        self.deleteHeadButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteHeadButton.sizePolicy().hasHeightForWidth())
        self.deleteHeadButton.setSizePolicy(sizePolicy)
        self.deleteHeadButton.setMinimumSize(QtCore.QSize(28, 24))
        self.deleteHeadButton.setMaximumSize(QtCore.QSize(28, 24))
        self.deleteHeadButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Remove the currently selected note head", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteHeadButton.setText(_fromUtf8(""))
        self.deleteHeadButton.setIcon(icon3)
        self.deleteHeadButton.setObjectName(_fromUtf8("deleteHeadButton"))
        self.horizontalLayout.addWidget(self.deleteHeadButton)
        spacerItem7 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        spacerItem8 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(editKitDialog)
        self.groupBox_4.setToolTip(QtGui.QApplication.translate("editKitDialog", "Mute audio in this dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("editKitDialog", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.muteButton = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.muteButton.sizePolicy().hasHeightForWidth())
        self.muteButton.setSizePolicy(sizePolicy)
        self.muteButton.setMaximumSize(QtCore.QSize(28, 24))
        self.muteButton.setToolTip(QtGui.QApplication.translate("editKitDialog", "Mute audio in this dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.muteButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/audio-volume-medium.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/audio-volume-muted.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.muteButton.setIcon(icon9)
        self.muteButton.setCheckable(True)
        self.muteButton.setObjectName(_fromUtf8("muteButton"))
        self.horizontalLayout_6.addWidget(self.muteButton)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setText(QtGui.QApplication.translate("editKitDialog", "Play sound effects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(editKitDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setToolTip(QtGui.QApplication.translate("editKitDialog", "The MIDI noise associated with this note head for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("editKitDialog", "MIDI Note", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.midiNoteCombo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiNoteCombo.sizePolicy().hasHeightForWidth())
        self.midiNoteCombo.setSizePolicy(sizePolicy)
        self.midiNoteCombo.setMinimumSize(QtCore.QSize(201, 0))
        self.midiNoteCombo.setToolTip(QtGui.QApplication.translate("editKitDialog", "The drum type associated with this note head for this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.midiNoteCombo.setObjectName(_fromUtf8("midiNoteCombo"))
        self.verticalLayout_5.addWidget(self.midiNoteCombo)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setToolTip(QtGui.QApplication.translate("editKitDialog", "The volume of this note head on this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("editKitDialog", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.volumeIndicator = QtGui.QLabel(self.groupBox_3)
        self.volumeIndicator.setToolTip(QtGui.QApplication.translate("editKitDialog", "The volume of this note head on this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeIndicator.setText(QtGui.QApplication.translate("editKitDialog", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeIndicator.setObjectName(_fromUtf8("volumeIndicator"))
        self.horizontalLayout_7.addWidget(self.volumeIndicator)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.volumeSlider = QtGui.QSlider(self.groupBox_3)
        self.volumeSlider.setToolTip(QtGui.QApplication.translate("editKitDialog", "The volume of this note head on this drum", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeSlider.setMaximum(127)
        self.volumeSlider.setSliderPosition(63)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setInvertedAppearance(False)
        self.volumeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.verticalLayout_4.addWidget(self.volumeSlider)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.effectsGroup = QtGui.QGroupBox(editKitDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effectsGroup.sizePolicy().hasHeightForWidth())
        self.effectsGroup.setSizePolicy(sizePolicy)
        self.effectsGroup.setMinimumSize(QtCore.QSize(221, 99))
        self.effectsGroup.setMaximumSize(QtCore.QSize(221, 99))
        self.effectsGroup.setToolTip(QtGui.QApplication.translate("editKitDialog", "Effects to apply to this note head", None, QtGui.QApplication.UnicodeUTF8))
        self.effectsGroup.setTitle(QtGui.QApplication.translate("editKitDialog", "Effects", None, QtGui.QApplication.UnicodeUTF8))
        self.effectsGroup.setObjectName(_fromUtf8("effectsGroup"))
        self.gridLayout = QtGui.QGridLayout(self.effectsGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.normalEffect = QtGui.QRadioButton(self.effectsGroup)
        self.normalEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "A normal strike", None, QtGui.QApplication.UnicodeUTF8))
        self.normalEffect.setText(QtGui.QApplication.translate("editKitDialog", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.normalEffect.setChecked(True)
        self.normalEffect.setObjectName(_fromUtf8("normalEffect"))
        self.gridLayout.addWidget(self.normalEffect, 0, 1, 1, 1)
        self.accentEffect = QtGui.QRadioButton(self.effectsGroup)
        self.accentEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "A harder strike", None, QtGui.QApplication.UnicodeUTF8))
        self.accentEffect.setText(QtGui.QApplication.translate("editKitDialog", "Accent", None, QtGui.QApplication.UnicodeUTF8))
        self.accentEffect.setObjectName(_fromUtf8("accentEffect"))
        self.gridLayout.addWidget(self.accentEffect, 0, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 4, 1, 1)
        self.ghostEffect = QtGui.QRadioButton(self.effectsGroup)
        self.ghostEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "A quieter strike", None, QtGui.QApplication.UnicodeUTF8))
        self.ghostEffect.setText(QtGui.QApplication.translate("editKitDialog", "Ghost", None, QtGui.QApplication.UnicodeUTF8))
        self.ghostEffect.setObjectName(_fromUtf8("ghostEffect"))
        self.gridLayout.addWidget(self.ghostEffect, 1, 1, 1, 1)
        self.chokeEffect = QtGui.QRadioButton(self.effectsGroup)
        self.chokeEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "A choked strike", None, QtGui.QApplication.UnicodeUTF8))
        self.chokeEffect.setText(QtGui.QApplication.translate("editKitDialog", "Choke", None, QtGui.QApplication.UnicodeUTF8))
        self.chokeEffect.setObjectName(_fromUtf8("chokeEffect"))
        self.gridLayout.addWidget(self.chokeEffect, 1, 3, 1, 1)
        self.flamEffect = QtGui.QRadioButton(self.effectsGroup)
        self.flamEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "A two-handed strike", None, QtGui.QApplication.UnicodeUTF8))
        self.flamEffect.setText(QtGui.QApplication.translate("editKitDialog", "Flam", None, QtGui.QApplication.UnicodeUTF8))
        self.flamEffect.setObjectName(_fromUtf8("flamEffect"))
        self.gridLayout.addWidget(self.flamEffect, 2, 1, 1, 1)
        self.dragEffect = QtGui.QRadioButton(self.effectsGroup)
        self.dragEffect.setToolTip(QtGui.QApplication.translate("editKitDialog", "Two or more strikes in quick succession", None, QtGui.QApplication.UnicodeUTF8))
        self.dragEffect.setText(QtGui.QApplication.translate("editKitDialog", "Drag", None, QtGui.QApplication.UnicodeUTF8))
        self.dragEffect.setObjectName(_fromUtf8("dragEffect"))
        self.gridLayout.addWidget(self.dragEffect, 2, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.effectsGroup)
        self.groupBox_2 = QtGui.QGroupBox(editKitDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setToolTip(QtGui.QApplication.translate("editKitDialog", "Should the drum line be locked?", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("editKitDialog", "Line Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lockedCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.lockedCheckBox.setToolTip(QtGui.QApplication.translate("editKitDialog", "Lock this line", None, QtGui.QApplication.UnicodeUTF8))
        self.lockedCheckBox.setText(_fromUtf8(""))
        self.lockedCheckBox.setObjectName(_fromUtf8("lockedCheckBox"))
        self.horizontalLayout_3.addWidget(self.lockedCheckBox)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(182, 48))
        self.label.setText(QtGui.QApplication.translate("editKitDialog", "The line for this drum will always be displayed, even if it contains no notes.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(editKitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_10.addWidget(self.buttonBox)
        self.label_3.setBuddy(self.drumName)
        self.label_4.setBuddy(self.drumAbbr)
        self.label_5.setBuddy(self.oldDrum)
        self.label_7.setBuddy(self.muteButton)
        self.label.setBuddy(self.lockedCheckBox)

        self.retranslateUi(editKitDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), editKitDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), editKitDialog.reject)
        QtCore.QObject.connect(self.volumeSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.volumeIndicator.setNum)
        QtCore.QMetaObject.connectSlotsByName(editKitDialog)
        editKitDialog.setTabOrder(self.addButton, self.deleteButton)
        editKitDialog.setTabOrder(self.deleteButton, self.clearButton)
        editKitDialog.setTabOrder(self.clearButton, self.loadButton)
        editKitDialog.setTabOrder(self.loadButton, self.saveButton)
        editKitDialog.setTabOrder(self.saveButton, self.buttonBox)

    def retranslateUi(self, editKitDialog):
        pass

import buttons_rc
import DrumBurp_rc
