# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\DrumBurp\src\GUI\drumburp.ui'
#
# Created: Tue Aug 03 01:59:43 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DrumBurpWindow(object):
    def setupUi(self, DrumBurpWindow):
        DrumBurpWindow.setObjectName("DrumBurpWindow")
        DrumBurpWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(DrumBurpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RadioButtonTeller = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller.setChecked(True)
        self.RadioButtonTeller.setObjectName("RadioButtonTeller")
        self.verticalLayout.addWidget(self.RadioButtonTeller)
        self.RadioButtonTeller_2 = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller_2.setObjectName("RadioButtonTeller_2")
        self.verticalLayout.addWidget(self.RadioButtonTeller_2)
        self.RadioButtonTeller_3 = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller_3.setObjectName("RadioButtonTeller_3")
        self.verticalLayout.addWidget(self.RadioButtonTeller_3)
        self.RadioButtonTeller_4 = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller_4.setObjectName("RadioButtonTeller_4")
        self.verticalLayout.addWidget(self.RadioButtonTeller_4)
        self.RadioButtonTeller_5 = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller_5.setObjectName("RadioButtonTeller_5")
        self.verticalLayout.addWidget(self.RadioButtonTeller_5)
        self.RadioButtonTeller_6 = RadioButtonTeller(self.groupBox)
        self.RadioButtonTeller_6.setObjectName("RadioButtonTeller_6")
        self.verticalLayout.addWidget(self.RadioButtonTeller_6)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.spaceSlider = QtGui.QSlider(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spaceSlider.sizePolicy().hasHeightForWidth())
        self.spaceSlider.setSizePolicy(sizePolicy)
        self.spaceSlider.setProperty("value", 50)
        self.spaceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.spaceSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.spaceSlider.setObjectName("spaceSlider")
        self.verticalLayout_2.addWidget(self.spaceSlider)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.frame_2 = QtGui.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtGui.QSpinBox(self.frame_2)
        self.spinBox.setMaximum(300)
        self.spinBox.setProperty("value", 120)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem1 = QtGui.QSpacerItem(154, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_2, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.scoreView = ScoreTable(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setWeight(50)
        font.setBold(False)
        self.scoreView.setFont(font)
        self.scoreView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.scoreView.setTabKeyNavigation(False)
        self.scoreView.setProperty("showDropIndicator", False)
        self.scoreView.setDragDropOverwriteMode(False)
        self.scoreView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.scoreView.setTextElideMode(QtCore.Qt.ElideNone)
        self.scoreView.setShowGrid(False)
        self.scoreView.setWordWrap(False)
        self.scoreView.setCornerButtonEnabled(False)
        self.scoreView.setObjectName("scoreView")
        self.scoreView.horizontalHeader().setVisible(False)
        self.scoreView.horizontalHeader().setDefaultSectionSize(10)
        self.scoreView.horizontalHeader().setHighlightSections(False)
        self.scoreView.horizontalHeader().setMinimumSectionSize(0)
        self.scoreView.verticalHeader().setDefaultSectionSize(10)
        self.scoreView.verticalHeader().setHighlightSections(False)
        self.scoreView.verticalHeader().setMinimumSectionSize(0)
        self.gridLayout_2.addWidget(self.scoreView, 1, 1, 1, 1)
        DrumBurpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DrumBurpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DrumBurpWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DrumBurpWindow)
        self.statusbar.setObjectName("statusbar")
        DrumBurpWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DrumBurpWindow)
        self.toolBar.setObjectName("toolBar")
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(DrumBurpWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtGui.QAction(DrumBurpWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtGui.QAction(DrumBurpWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(DrumBurpWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(DrumBurpWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport_ASCII = QtGui.QAction(DrumBurpWindow)
        self.actionExport_ASCII.setObjectName("actionExport_ASCII")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_ASCII)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionQuit)
        self.label.setBuddy(self.lineEdit)
        self.label_3.setBuddy(self.spinBox)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_4.setBuddy(self.lineEdit_3)

        self.retranslateUi(DrumBurpWindow)
        QtCore.QObject.connect(self.spaceSlider, QtCore.SIGNAL("valueChanged(int)"), self.scoreView.spacingChanged)
        QtCore.QObject.connect(self.RadioButtonTeller, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.RadioButtonTeller_2, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.RadioButtonTeller_3, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.RadioButtonTeller_4, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.RadioButtonTeller_5, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.RadioButtonTeller_6, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QMetaObject.connectSlotsByName(DrumBurpWindow)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller, self.RadioButtonTeller_2)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller_2, self.RadioButtonTeller_3)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller_3, self.RadioButtonTeller_4)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller_4, self.RadioButtonTeller_5)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller_5, self.RadioButtonTeller_6)
        DrumBurpWindow.setTabOrder(self.RadioButtonTeller_6, self.pushButton)
        DrumBurpWindow.setTabOrder(self.pushButton, self.spaceSlider)
        DrumBurpWindow.setTabOrder(self.spaceSlider, self.lineEdit)
        DrumBurpWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        DrumBurpWindow.setTabOrder(self.lineEdit_2, self.spinBox)
        DrumBurpWindow.setTabOrder(self.spinBox, self.lineEdit_3)
        DrumBurpWindow.setTabOrder(self.lineEdit_3, self.scoreView)

    def retranslateUi(self, DrumBurpWindow):
        DrumBurpWindow.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Note Head", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller.setText(QtGui.QApplication.translate("DrumBurpWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_2.setText(QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_2.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_3.setText(QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_3.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_4.setText(QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_4.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_5.setText(QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_5.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_6.setText(QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioButtonTeller_6.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DrumBurpWindow", "Horizontal Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DrumBurpWindow", "Song", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DrumBurpWindow", "BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DrumBurpWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DrumBurpWindow", "Tabbed by", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setSuffix(QtGui.QApplication.translate("DrumBurpWindow", " bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DrumBurpWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DrumBurpWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("DrumBurpWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_ASCII.setText(QtGui.QApplication.translate("DrumBurpWindow", "Export ASCII", None, QtGui.QApplication.UnicodeUTF8))

from Widgets.RadioButtonTeller_plugin import RadioButtonTeller
from Widgets.ScoreTable_plugin import ScoreTable
