# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\DrumBurp\src\GUI\drumburp.ui'
#
# Created: Wed Oct 06 23:57:19 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DrumBurpWindow(object):
    def setupUi(self, DrumBurpWindow):
        DrumBurpWindow.setObjectName("DrumBurpWindow")
        DrumBurpWindow.resize(800, 600)
        DrumBurpWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(DrumBurpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.optionsFrame = QtGui.QFrame(self.centralwidget)
        self.optionsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.optionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.optionsFrame.setObjectName("optionsFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.optionsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.noteHeadGroupBox = QtGui.QGroupBox(self.optionsFrame)
        self.noteHeadGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.noteHeadGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.noteHeadGroupBox.setObjectName("noteHeadGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.noteHeadGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.defaultNoteHeadButton.setChecked(True)
        self.defaultNoteHeadButton.setObjectName("defaultNoteHeadButton")
        self.verticalLayout.addWidget(self.defaultNoteHeadButton)
        self.xNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.xNoteHeadButton.setObjectName("xNoteHeadButton")
        self.verticalLayout.addWidget(self.xNoteHeadButton)
        self.bigXNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.bigXNoteHeadButton.setObjectName("bigXNoteHeadButton")
        self.verticalLayout.addWidget(self.bigXNoteHeadButton)
        self.oNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.oNoteHeadButton.setObjectName("oNoteHeadButton")
        self.verticalLayout.addWidget(self.oNoteHeadButton)
        self.bigONoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.bigONoteHeadButton.setObjectName("bigONoteHeadButton")
        self.verticalLayout.addWidget(self.bigONoteHeadButton)
        self.plusNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.plusNoteHeadButton.setObjectName("plusNoteHeadButton")
        self.verticalLayout.addWidget(self.plusNoteHeadButton)
        self.gNoteHeadButton = RadioButtonTeller(self.noteHeadGroupBox)
        self.gNoteHeadButton.setObjectName("gNoteHeadButton")
        self.verticalLayout.addWidget(self.gNoteHeadButton)
        self.verticalLayout_2.addWidget(self.noteHeadGroupBox)
        self.displayOptionsGroupBox = QtGui.QGroupBox(self.optionsFrame)
        self.displayOptionsGroupBox.setObjectName("displayOptionsGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.displayOptionsGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spacingLabel = QtGui.QLabel(self.displayOptionsGroupBox)
        self.spacingLabel.setWordWrap(True)
        self.spacingLabel.setObjectName("spacingLabel")
        self.verticalLayout_3.addWidget(self.spacingLabel)
        self.spaceSlider = QtGui.QSlider(self.displayOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spaceSlider.sizePolicy().hasHeightForWidth())
        self.spaceSlider.setSizePolicy(sizePolicy)
        self.spaceSlider.setProperty("value", 0)
        self.spaceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.spaceSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.spaceSlider.setObjectName("spaceSlider")
        self.verticalLayout_3.addWidget(self.spaceSlider)
        self.widthLabel = QtGui.QLabel(self.displayOptionsGroupBox)
        self.widthLabel.setObjectName("widthLabel")
        self.verticalLayout_3.addWidget(self.widthLabel)
        self.widthGroupBox = QtGui.QFrame(self.displayOptionsGroupBox)
        self.widthGroupBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.widthGroupBox.setFrameShadow(QtGui.QFrame.Raised)
        self.widthGroupBox.setObjectName("widthGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widthGroupBox)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fixedWidthCheckBox = QtGui.QCheckBox(self.widthGroupBox)
        self.fixedWidthCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fixedWidthCheckBox.setChecked(True)
        self.fixedWidthCheckBox.setObjectName("fixedWidthCheckBox")
        self.horizontalLayout_2.addWidget(self.fixedWidthCheckBox)
        self.widthSpinBox = QtGui.QSpinBox(self.widthGroupBox)
        self.widthSpinBox.setMinimum(10)
        self.widthSpinBox.setMaximum(1000)
        self.widthSpinBox.setProperty("value", 80)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout_2.addWidget(self.widthSpinBox)
        self.verticalLayout_3.addWidget(self.widthGroupBox)
        self.verticalLayout_2.addWidget(self.displayOptionsGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.optionsFrame, 0, 0, 2, 1)
        self.songPropertiesGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.songPropertiesGroupBox.setObjectName("songPropertiesGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.songPropertiesGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.songNameLabel = QtGui.QLabel(self.songPropertiesGroupBox)
        self.songNameLabel.setObjectName("songNameLabel")
        self.gridLayout.addWidget(self.songNameLabel, 0, 0, 1, 1)
        self.songNameEdit = QtGui.QLineEdit(self.songPropertiesGroupBox)
        self.songNameEdit.setObjectName("songNameEdit")
        self.gridLayout.addWidget(self.songNameEdit, 0, 1, 1, 1)
        self.bpmLabel = QtGui.QLabel(self.songPropertiesGroupBox)
        self.bpmLabel.setObjectName("bpmLabel")
        self.gridLayout.addWidget(self.bpmLabel, 0, 2, 1, 1)
        self.artistNameLabel = QtGui.QLabel(self.songPropertiesGroupBox)
        self.artistNameLabel.setObjectName("artistNameLabel")
        self.gridLayout.addWidget(self.artistNameLabel, 1, 0, 1, 1)
        self.artistNameEdit = QtGui.QLineEdit(self.songPropertiesGroupBox)
        self.artistNameEdit.setObjectName("artistNameEdit")
        self.gridLayout.addWidget(self.artistNameEdit, 1, 1, 1, 1)
        self.tabberLabel = QtGui.QLabel(self.songPropertiesGroupBox)
        self.tabberLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.tabberLabel.setObjectName("tabberLabel")
        self.gridLayout.addWidget(self.tabberLabel, 1, 2, 1, 1)
        self.tabberEdit = QtGui.QLineEdit(self.songPropertiesGroupBox)
        self.tabberEdit.setObjectName("tabberEdit")
        self.gridLayout.addWidget(self.tabberEdit, 1, 3, 1, 1)
        self.bpmFrame = QtGui.QFrame(self.songPropertiesGroupBox)
        self.bpmFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bpmFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.bpmFrame.setObjectName("bpmFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.bpmFrame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bpmSpinBox = QtGui.QSpinBox(self.bpmFrame)
        self.bpmSpinBox.setMaximum(300)
        self.bpmSpinBox.setProperty("value", 120)
        self.bpmSpinBox.setObjectName("bpmSpinBox")
        self.horizontalLayout.addWidget(self.bpmSpinBox)
        spacerItem1 = QtGui.QSpacerItem(154, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.bpmFrame, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.songPropertiesGroupBox, 0, 1, 1, 1)
        self.scoreView = ScoreTable(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreView.sizePolicy().hasHeightForWidth())
        self.scoreView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setWeight(50)
        font.setBold(False)
        self.scoreView.setFont(font)
        self.scoreView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scoreView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.scoreView.setTabKeyNavigation(False)
        self.scoreView.setProperty("showDropIndicator", False)
        self.scoreView.setDragDropOverwriteMode(False)
        self.scoreView.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.scoreView.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.scoreView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.scoreView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.scoreView.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.scoreView.setShowGrid(False)
        self.scoreView.setGridStyle(QtCore.Qt.NoPen)
        self.scoreView.setWordWrap(False)
        self.scoreView.setCornerButtonEnabled(False)
        self.scoreView.setObjectName("scoreView")
        self.scoreView.horizontalHeader().setVisible(False)
        self.scoreView.horizontalHeader().setDefaultSectionSize(0)
        self.scoreView.horizontalHeader().setHighlightSections(False)
        self.scoreView.horizontalHeader().setMinimumSectionSize(0)
        self.scoreView.verticalHeader().setDefaultSectionSize(0)
        self.scoreView.verticalHeader().setHighlightSections(False)
        self.scoreView.verticalHeader().setMinimumSectionSize(0)
        self.gridLayout_2.addWidget(self.scoreView, 1, 1, 1, 1)
        DrumBurpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DrumBurpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DrumBurpWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DrumBurpWindow)
        self.statusbar.setObjectName("statusbar")
        DrumBurpWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DrumBurpWindow)
        self.toolBar.setObjectName("toolBar")
        DrumBurpWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(DrumBurpWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtGui.QAction(DrumBurpWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtGui.QAction(DrumBurpWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(DrumBurpWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(DrumBurpWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport_ASCII = QtGui.QAction(DrumBurpWindow)
        self.actionExport_ASCII.setObjectName("actionExport_ASCII")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_ASCII)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionQuit)
        self.spacingLabel.setBuddy(self.spaceSlider)
        self.songNameLabel.setBuddy(self.songNameEdit)
        self.bpmLabel.setBuddy(self.bpmSpinBox)
        self.artistNameLabel.setBuddy(self.artistNameEdit)
        self.tabberLabel.setBuddy(self.tabberEdit)

        self.retranslateUi(DrumBurpWindow)
        QtCore.QObject.connect(self.spaceSlider, QtCore.SIGNAL("valueChanged(int)"), self.scoreView.spacingChanged)
        QtCore.QObject.connect(self.defaultNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.xNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.bigXNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.oNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.bigONoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.plusNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QObject.connect(self.fixedWidthCheckBox, QtCore.SIGNAL("clicked(bool)"), self.widthSpinBox.setEnabled)
        QtCore.QObject.connect(self.widthSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.scoreView.setWidth)
        QtCore.QObject.connect(self.fixedWidthCheckBox, QtCore.SIGNAL("clicked(bool)"), self.scoreView.setFixedWidth)
        QtCore.QObject.connect(self.gNoteHeadButton, QtCore.SIGNAL("emitValue(QString)"), self.scoreView.setNoteHead)
        QtCore.QMetaObject.connectSlotsByName(DrumBurpWindow)
        DrumBurpWindow.setTabOrder(self.defaultNoteHeadButton, self.xNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.xNoteHeadButton, self.bigXNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.bigXNoteHeadButton, self.oNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.oNoteHeadButton, self.bigONoteHeadButton)
        DrumBurpWindow.setTabOrder(self.bigONoteHeadButton, self.plusNoteHeadButton)
        DrumBurpWindow.setTabOrder(self.plusNoteHeadButton, self.songNameEdit)
        DrumBurpWindow.setTabOrder(self.songNameEdit, self.artistNameEdit)
        DrumBurpWindow.setTabOrder(self.artistNameEdit, self.bpmSpinBox)
        DrumBurpWindow.setTabOrder(self.bpmSpinBox, self.tabberEdit)
        DrumBurpWindow.setTabOrder(self.tabberEdit, self.scoreView)

    def retranslateUi(self, DrumBurpWindow):
        DrumBurpWindow.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.noteHeadGroupBox.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Note Head", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.xNoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.bigXNoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.oNoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.bigONoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.plusNoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setText(QtGui.QApplication.translate("DrumBurpWindow", "g", None, QtGui.QApplication.UnicodeUTF8))
        self.gNoteHeadButton.setProperty("buttonValue", QtGui.QApplication.translate("DrumBurpWindow", "g", None, QtGui.QApplication.UnicodeUTF8))
        self.displayOptionsGroupBox.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Display Options", None, QtGui.QApplication.UnicodeUTF8))
        self.spacingLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Horizontal Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedWidthCheckBox.setText(QtGui.QApplication.translate("DrumBurpWindow", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.songPropertiesGroupBox.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "Song Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.songNameLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "&BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.artistNameLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "&Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.tabberLabel.setText(QtGui.QApplication.translate("DrumBurpWindow", "&Tabbed by", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmSpinBox.setSuffix(QtGui.QApplication.translate("DrumBurpWindow", " bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DrumBurpWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DrumBurpWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DrumBurpWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("DrumBurpWindow", "Quit DrumBurp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DrumBurpWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("DrumBurpWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("DrumBurpWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_ASCII.setText(QtGui.QApplication.translate("DrumBurpWindow", "Export ASCII", None, QtGui.QApplication.UnicodeUTF8))

from Widgets.RadioButtonTeller_plugin import RadioButtonTeller
from Widgets.ScoreTable_plugin import ScoreTable
